import * as T from './vendor/three.module.js';
import {START,END,TURN_RATE,center,height,floorHeight,move,boundedHead,axis,direction,clamp} from './navigation.js';
import {createWorld} from './world.js';
import {Soundscape} from './audio.js';
const $=id=>document.getElementById(id);
let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('error').hidden=false;$('error').textContent='This browser could not start WebGL. Please open Stillwater in Meta Quest Browser or a browser with hardware acceleration.';throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');renderer.xr.setFramebufferScaleFactor(1);renderer.xr.setFoveation(1);$('world').appendChild(renderer.domElement);
const scene=new T.Scene(),rig=new T.Group(),camera=new T.PerspectiveCamera(65,innerWidth/innerHeight,.08,240);rig.position.set(center(START),floorHeight(center(START),START),START);camera.position.set(0,1.65,0);rig.add(camera);scene.add(rig);const world=createWorld(scene),audio=new Soundscape();
const keys=new Set(),touch=new Set(),head=new T.Vector3(),localHead=new T.Vector3(),headQ=new T.Quaternion(),rigQ=new T.Quaternion(),forward=new T.Vector3(),ray=new T.Raycaster();let playing=false,opened=false,near=false,frames=0,lastTime=0,walked=0,nextChime=35,drag=null,pitch=0,session=null,paused=false;const controllers=[];
function soundLabel(){$('sound').textContent=audio.enabled?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(audio.enabled))}
async function startAudio(){try{await audio.start();soundLabel()}catch(e){$('hint').textContent='Audio could not start; walking is still available.'}}
function begin(){playing=true;document.body.classList.add('walking');$('journey').hidden=false;$('home').hidden=false;$('touch').hidden=!matchMedia('(pointer:coarse)').matches;$('hint').textContent='WASD to walk · drag to look · Q / E to turn';startAudio()}
function restart(){rig.position.set(center(START),floorHeight(center(START),START),START);rig.rotation.y=0;camera.rotation.set(0,0,0);pitch=0;opened=false;world.slate.visible=false;$('greeting').hidden=true;keys.clear();touch.clear()}
function greet(){if(!near)return;opened=!opened;world.slate.visible=opened;$('greeting').hidden=!opened;audio.chime()}
$('walk').onclick=begin;$('home').onclick=restart;$('knock').onclick=greet;$('close-greeting').onclick=()=>{$('greeting').hidden=true};$('sound').onclick=()=>{if(audio.enabled){audio.stop();soundLabel()}else startAudio()};
$('walk').disabled=false;$('walk').textContent='Walk the path';
async function checkVR(){try{if(navigator.xr&&await navigator.xr.isSessionSupported('immersive-vr')){$('vr').disabled=false;$('vr').textContent='Enter VR'}else{$('vr').textContent='VR headset required';$('support').textContent='For immersive VR, open this page in Meta Quest Browser.'}}catch(e){$('vr').textContent='VR unavailable'}}checkVR();
$('vr').onclick=async()=>{try{$('vr').disabled=true;const s=await navigator.xr.requestSession('immersive-vr',{requiredFeatures:['local-floor'],optionalFeatures:['bounded-floor']});session=s;await renderer.xr.setSession(s);begin();document.body.classList.add('xr');s.addEventListener('visibilitychange',()=>{paused=s.visibilityState!=='visible';if(paused){keys.clear();touch.clear()}});s.addEventListener('end',()=>{session=null;paused=false;document.body.classList.remove('xr');camera.position.set(0,1.65,0);camera.rotation.set(pitch,0,0);$('vr').disabled=false;$('vr').textContent='Enter VR'});if(s.updateTargetFrameRate&&s.supportedFrameRates?.includes(72))s.updateTargetFrameRate(72).catch(()=>{});}catch(e){$('vr').disabled=false;$('support').textContent='VR could not start. Check headset permissions and try again.'}};
// Visible rays use the standard target-ray spaces. Selecting either controller also
// supports the forgiving near-door trigger so users need not aim at a tiny handle.
for(let i=0;i<2;i++){const c=renderer.xr.getController(i),line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-1)]),new T.LineBasicMaterial({color:0xe8cd94,transparent:true,opacity:.75}));line.scale.z=3;c.add(line);rig.add(c);c.addEventListener('select',()=>{if(near)greet()});controllers.push(c)}
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='f'&&!e.repeat)greet();if(e.key==='Escape'){$('greeting').hidden=true;keys.clear()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();touch.clear();drag=null});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();touch.clear()}});
renderer.domElement.addEventListener('pointerdown',e=>{if(!playing)return;drag={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||session)return;rig.rotation.y-=(e.clientX-drag.x)*.003;pitch=clamp(pitch-(e.clientY-drag.y)*.003,-1.25,1.25);camera.rotation.x=pitch;drag={x:e.clientX,y:e.clientY}});for(const event of ['pointerup','pointercancel','lostpointercapture'])renderer.domElement.addEventListener(event,()=>drag=null);
for(const b of document.querySelectorAll('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();touch.add(b.dataset.move);b.setPointerCapture(e.pointerId)});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,()=>touch.delete(b.dataset.move))}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
function readHead(frame){if(frame){const pose=frame.getViewerPose(renderer.xr.getReferenceSpace());if(pose){localHead.set(pose.transform.position.x,pose.transform.position.y,pose.transform.position.z);headQ.set(pose.transform.orientation.x,pose.transform.orientation.y,pose.transform.orientation.z,pose.transform.orientation.w)}else return false}else{localHead.copy(camera.position);headQ.copy(camera.quaternion)}rigQ.setFromAxisAngle(T.Object3D.DEFAULT_UP,rig.rotation.y);head.copy(localHead).applyQuaternion(rigQ).add(rig.position);return true}
function update(time,frame){const dt=Math.min((time-lastTime)/1000||0,.05);lastTime=time;frames++;const t=time/1000;world.update(t,opened,dt);if(readHead(frame)&&playing&&!paused&&!document.hidden){let x=0,y=0,turn=0;if(session){for(const input of session.inputSources){const a=input.gamepad?.axes;if(!a)continue;const ax=a.length>=4?a[2]:a[0],ay=a.length>=4?a[3]:a[1];if(input.handedness==='left'){x=axis(ax||0);y=axis(ay||0)}if(input.handedness==='right')turn=axis(ax||0)}}else{x=Number(keys.has('d')||keys.has('arrowright')||touch.has('right'))-Number(keys.has('a')||keys.has('arrowleft')||touch.has('left'));y=Number(keys.has('s')||keys.has('arrowdown')||touch.has('back'))-Number(keys.has('w')||keys.has('arrowup')||touch.has('forward'));turn=Number(keys.has('e'))-Number(keys.has('q'))}
 // Rotate about the tracked head, never about a distant rig origin.
 if(turn){const oldX=head.x,oldZ=head.z;rig.rotation.y-=turn*TURN_RATE*dt;readHead(frame);rig.position.x+=oldX-head.x;rig.position.z+=oldZ-head.z;readHead(frame)}
 forward.set(0,0,-1).applyQuaternion(headQ).applyQuaternion(rigQ);const yaw=Math.atan2(-forward.x,-forward.z);const delta=direction(yaw,x,y,dt),target=move(head,delta.dx,delta.dz);const d=Math.hypot(target.x-head.x,target.z-head.z);rig.position.x+=target.x-head.x;rig.position.z+=target.z-head.z;walked+=d;if(walked>.8){walked=0;audio.step()}
 readHead(frame);const b=boundedHead(head.x,head.z);rig.position.x+=b.x-head.x;rig.position.z+=b.z-head.z;rig.position.y=floorHeight(b.x,b.z);readHead(frame);
 near=Math.hypot(head.x,head.z+40.8)<2.9;$('knock').hidden=!near;const remaining=Math.max(0,head.z-END);$('distance').textContent=near?'You have arrived':Math.round(remaining)+' m to the observatory';$('progress').style.width=((START-head.z)/(START-END)*100)+'%';if(t>nextChime&&audio.enabled){audio.chime();nextChime=t+45}
 }renderer.render(scene,camera)}
renderer.setAnimationLoop(update);
// Read-only diagnostics remain available for headset profiling. Test positioning
// is enabled solely on loopback hosts and cannot be invoked on the public page.
window.Stillwater={snapshot:()=>({frames,playing,xr:renderer.xr.isPresenting,position:{x:head.x,y:head.y,z:head.z},rig:{x:rig.position.x,y:rig.position.y,z:rig.position.z,yaw:rig.rotation.y},near,opened,doorAngle:world.doorPivot.rotation.y,audio:audio.enabled,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures})};
if(['127.0.0.1','localhost'].includes(location.hostname)){window.Stillwater.place=(z,x=center(z),yaw=0)=>{rig.position.set(x,floorHeight(x,z),z);rig.rotation.y=yaw;camera.rotation.set(0,0,0);pitch=0};window.Stillwater.scene=scene;window.Stillwater.camera=camera;window.Stillwater.renderer=renderer;}
